select * from ubigeo

insert into Dialecto(NomDial)

values
('Español'),
('Inglés'),
('Chino mandarín'),
('Francés'),
('Italiano'),
('Portugués'),
('Ruso'),
('Alemán'),
('Japonés'),
('Griego'),
('Coreano'),
('Árabe'),
('Rumano'),
('Hindi-Urdú'),
('Sueco'),
('Neerlandés'),
('Polaco'),
('Servo-Croata'),
('Húngaro'),
('Checo'),
('Búlgaro'),
('Ucraniano'),
('Zulú'),
('Vietnamita'),
('Arabe Saidi'),
('Farsi o Persa'),
('Chino Zhuang'),
('Lombardo'),
('Bengalí'),
('Malayo'),
('Chino Harka'),
('Yoruba'),
('Arabe marroquí'),
('Oromo'),
('Thai'),
('Akan'),
('Arabe mesopotámico'),
('Arabe sanaani'),
('Tagalo'),
('Chino Cantonés-Yue'),
('Haitiano Criollo Francés'),
('Igbo'),
('Chino Gan'),
('Nepalí'),
('Arabe sirio'),
('Arabe egipcio'),
('Tamil'),
('Amharic'),
('Chittaginiano'),
('Belarusano'),
('Rwandés'),
('Arabe sudanés'),
('Malayo-Indonesio'),
('Azerbaiyano'),
('Azerí o Azerbaiyano'),
('Mahahi'),
('Chino Wu'),
('Canarés o Kannada'),
('Javanés'),
('Haryanvi'),
('Telugu'),
('Madura'),
('Kauki'),
('Quechua'),
('Jakaru');
