-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2018-09-25 16:28:26.736

-- tables
-- Table: AREATRABAJO
CREATE TABLE AREATRABAJO (
    IDARE integer,
    NOMARE varchar2(50),
    TIPOTRA varchar2(50),
    CONSTRAINT AREATRABAJO_pk PRIMARY KEY (IDARE)
) ;

-- Table: ENFERMEDADES
CREATE TABLE ENFERMEDADES (
    IDENFER integer,
    CODIGOENFER char(6),
    NOMENFER varchar2(300),
    CONSTRAINT ENFERMEDADES_pk PRIMARY KEY (IDENFER)
) ;

-- Table: ESPECIALIDAD
CREATE TABLE ESPECIALIDAD (
    IDESP integer,
    NOMESP varchar2(50),
    CONSTRAINT ESPECIALIDAD_pk PRIMARY KEY (IDESP)
) ;

-- Table: EXAM_FISICO
CREATE TABLE EXAM_FISICO (
    IDEXAFI integer,
    ESTEXFI varchar2(50),
    CONSTRAINT EXAM_FISICO_pk PRIMARY KEY (IDEXAFI)
) ;

-- Table: HISTORIA_CLINICA
CREATE TABLE HISTORIA_CLINICA (
    IDHIS integer,
    FECHIS date,
    PACIENTE_IDPAC integer,
    PRFECHIS date,
    TRATAMIENTO_IDTRA integer,
    ENFERMEDADES_IDENFER integer,
    CONSTRAINT HISTORIA_CLINICA_pk PRIMARY KEY (IDHIS)
) ;

-- Table: MEDICO
CREATE TABLE MEDICO (
    IDMED integer,
    NOMMED varchar2(50),
    APEMED varchar2(50),
    DNIMED char(8),
    SEXOMED varchar2(9),
    TELFMED char(7),
    GMAILMED varchar2(50)  NULL,
    ESPECIALIDAD_IDESP integer,
    CONSTRAINT MEDICO_pk PRIMARY KEY (IDMED)
) ;

-- Table: PACIENTE
CREATE TABLE PACIENTE (
    IDPAC integer,
    APEPAC varchar2(50),
    NOMPAC varchar2(50),
    DNIPAC char(8),
    SEXPAC varchar2(20),
    FECHNACPAC date,
    LUGNACPAC varchar2(50),
    PROCEPAC varchar2(50),
    CEEDUPAC varchar2(50)  NULL,
    GRAINSTRUCPAC varchar2(50)  NULL,
    GRUPANGPAC varchar2(50),
    TELFPAC char(7)  NULL,
    ESTCIVPAC varchar2(50)  NULL,
    OCUPAC varchar2(50)  NULL,
    TIPOPAC_IDPAC integer,
    CONSTRAINT PACIENTE_pk PRIMARY KEY (IDPAC)
) ;

-- Table: TIPOPAC
CREATE TABLE TIPOPAC (
    IDPAC integer,
    NOMTIP varchar2(50),
    CONSTRAINT TIPOPAC_pk PRIMARY KEY (IDPAC)
) ;

-- Table: TRATAMIENTO
CREATE TABLE TRATAMIENTO (
    IDTRA integer,
    NOMTRA varchar2(200),
    MEDICO_IDMED integer,
    AREATRABAJO_IDARE integer,
    CONSTRAINT TRATAMIENTO_pk PRIMARY KEY (IDTRA)
) ;

-- Table: TRIAGE
CREATE TABLE TRIAGE (
    IDAGE integer,
    PESAGE char(3),
    TEMAGE char(5),
    PULAGE varchar2(50),
    CONSTRAINT TRIAGE_pk PRIMARY KEY (IDAGE)
) ;

-- Table: VACUNACION
CREATE TABLE VACUNACION (
    IDVAC integer,
    NOMVAC varchar2(50),
    CONSTRAINT VACUNACION_pk PRIMARY KEY (IDVAC)
) ;

-- foreign keys
-- Reference: HISTORIA_CLINICA_ENFERMEDADES (table: HISTORIA_CLINICA)
ALTER TABLE HISTORIA_CLINICA ADD CONSTRAINT HISTORIA_CLINICA_ENFERMEDADES
    FOREIGN KEY (ENFERMEDADES_IDENFER)
    REFERENCES ENFERMEDADES (IDENFER);

-- Reference: HISTORIA_CLINICA_PACIENTE (table: HISTORIA_CLINICA)
ALTER TABLE HISTORIA_CLINICA ADD CONSTRAINT HISTORIA_CLINICA_PACIENTE
    FOREIGN KEY (PACIENTE_IDPAC)
    REFERENCES PACIENTE (IDPAC);

-- Reference: HISTORIA_CLINICA_TRATAMIENTO (table: HISTORIA_CLINICA)
ALTER TABLE HISTORIA_CLINICA ADD CONSTRAINT HISTORIA_CLINICA_TRATAMIENTO
    FOREIGN KEY (TRATAMIENTO_IDTRA)
    REFERENCES TRATAMIENTO (IDTRA);

-- Reference: MEDICO_ESPECIALIDAD (table: MEDICO)
ALTER TABLE MEDICO ADD CONSTRAINT MEDICO_ESPECIALIDAD
    FOREIGN KEY (ESPECIALIDAD_IDESP)
    REFERENCES ESPECIALIDAD (IDESP);

-- Reference: PACIENTE_TIPOPAC (table: PACIENTE)
ALTER TABLE PACIENTE ADD CONSTRAINT PACIENTE_TIPOPAC
    FOREIGN KEY (TIPOPAC_IDPAC)
    REFERENCES TIPOPAC (IDPAC);

-- Reference: TRATAMIENTO_AREATRABAJO (table: TRATAMIENTO)
ALTER TABLE TRATAMIENTO ADD CONSTRAINT TRATAMIENTO_AREATRABAJO
    FOREIGN KEY (AREATRABAJO_IDARE)
    REFERENCES AREATRABAJO (IDARE);

-- Reference: TRATAMIENTO_MEDICO (table: TRATAMIENTO)
ALTER TABLE TRATAMIENTO ADD CONSTRAINT TRATAMIENTO_MEDICO
    FOREIGN KEY (MEDICO_IDMED)
    REFERENCES MEDICO (IDMED);

-- End of file.

